#!/usr/bin/env bash

# ====== Variables =============================

gaps_top="26"
gaps_bottom="0"
gaps_left="0"
gaps_right="0"
gaps_inner="5"


# ====== Tiling settings =======================

# 使用 font-awesome 替代罗马数字
 yabai -m config layout                      bsp

# bar settings

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

yabai -m config window_border               off

# ====== Confituration spaces ==================
init_space() {
    space_number=$1
    space_name=$2
    space_layout=$3
    yabai -m space $space_name --balance
    if [[ $? == 0 ]]
    then
       return 0
    fi

    if [[ $space_layout=="" ]]
    then
        space_layout=bsp
    fi

    yabai -m space $space_name --balance || yabai -m space $space_number --layout $space_layout || yabai -m space --create
    yabai -m space $space_name --balance || yabai -m space $space_number --label $space_name
}

init_space 1 editor
init_space 2 terminal
init_space 3 browser1
init_space 4 browser2
init_space 5 docs
init_space 6 chat float
init_space 7 media
init_space 8 remote1
init_space 9 remote2
init_space 10 vms

# ====== List of rules =========================

yabai -m rule --add label=chrome app="^Google Chrome$" space=browser2

# ====== List of rules =========================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off

# ====== 规则列表 ===============================
yabai -m rule --add label="系统偏好设置" app="^系统偏好设置$" manage=off
yabai -m rule --add label="Parallels Desktop" app="^Parallels Desktop$" manage=off
yabai -m rule --add label="企业微信" app="^企业微信$" manage=off
yabai -m rule --add label="微信" app="^微信$" manage=off
yabai -m rule --add label="网易云音乐" app="^网易云音乐$" manage=off
yabai -m rule --add label="MenuMeters" app="^MenuMeters$" manage=off
yabai -m rule --add label="预览" app="^预览$" manage=off
