#!/usr/bin/env sh

export PATH=~/.local/share/bin/statusbar:~/.local/share/bin:$PATH
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -d -x
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
export TERMINAL=xfce4-terminal
## Local Variables:
## mode: shell-script
## End;
