#!/usr/bin/env sh

export PATH=~/.local/share/bin/statusbar:~/.local/share/bin:$PATH
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -d -x


## Local Variables:
## mode: shell-script
## End;
